import Head from 'next/head'
import Image from 'next/image'
import 'bootstrap/dist/css/bootstrap.min.css';
import { Inter } from 'next/font/google'
import styles from '@components/styles/Home.module.css'
import Namebar from './components/Namebar'
import {Homepage} from './Homepage'
import { useRouter } from 'next/router';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
      <title>Ovidots Journal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Namebar/>
      <Homepage />
    </>
  )
}
